# Generated by Django 3.2.8 on 2023-06-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idSolicitud', models.IntegerField()),
                ('fechaSolicitud', models.DateTimeField()),
                ('idUsuario', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descipción')),
                ('fotoUbicacion', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('direccionIncidente', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('idSeguimeinto', models.IntegerField(null=True)),
            ],
        ),
    ]
