# Generated by Django 3.2.8 on 2023-06-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes311', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='idSeguimeinto',
            new_name='idSeguimiento',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descipcion'),
        ),
    ]
