# Generated by Django 3.2.8 on 2023-08-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes311', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='idUsuario',
            field=models.CharField(max_length=200, verbose_name='IdUsuario'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='idUsuario',
            field=models.CharField(max_length=200, verbose_name='IDUsuario'),
        ),
    ]
